### PR TITLE
Bootstrap-ify change.tmpl

### PR DESCRIPTION
**Pull request by nicoonoclaste**
I used a patched `recentchanges.pm` to split the commit message into title and body.
This is not-so-great, and I would be glad to learn a cleaner solution.

### CODE REVIEW

**Comment by gsliepen** [comment]
On Sat, Oct 01, 2016 at 06:06:03AM -0700, Nicolas Braud-Santoni wrote:

> I used a patched `recentchanges.pm` to split the commit message into title and body.
> This is not-so-great, and I would be glad to learn a cleaner solution.
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/gsliepen/ikistrap/pull/6

Unfortunately, it fails to work properly on my machine:

```
HTML_TIDY=./tidy.config ikiwiki --setup example.setup --refresh
Failed to load plugin IkiWiki::Plugin::recentchanges: Experimental shift on scalar is now forbidden at lib/IkiWiki/Plugin/recentchanges.pm line 217, near "};"
Compilation failed in require at (eval 41) line 2.
BEGIN failed--compilation aborted at (eval 41) line 2.
```

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by nicoonoclaste** [comment]
@gsliepen I'm not sure what is causing this (I'm not a Perl expert and the issue doesn't occur on Debian Stretch).
In any case, I just pushed something that should hopefully work better.

**Comment by gsliepen** [comment]
Works fine now, merged.

**Comment by nicoonoclaste** [comment]
@gsliepen Not merged.

**Pull request closed without merging**
