### PR TITLE
Better ressource handling

### PR DESCRIPTION
**Pull request by nicoonoclaste**
- [x] Use Sub-Ressource Integrity when referring to CDN ressources.
    This prevents the CDN from injecting unexpected content.
- [x] Load CSS before Javascript.
    Some browsers otherwise disable parallel fetches.

### CODE REVIEW

**Comment by gsliepen** [comment]
On Sat, Sep 17, 2016 at 06:15:41PM -0700, Nicolas Braud-Santoni wrote:

> - [x] Use Sub-Ressource Integrity when referring to CDN ressources.
>     This prevents the CDN from injecting unexpected content.
> - [x] Load CSS before Javascript.
>     Some browsers otherwise disable parallel fetches.

Great, especially the SRI changes!

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by nicoonoclaste** [comment]
Indeed.

Unfortunately, I discovered there is nothing like SRI for fonts, so I guess the recommended solution should be to host fonts locally (which is kinda suboptimal, cache-wise).

**Comment by nicoonoclaste** [comment]
@gsliepen Is there anything blocking, for this PR?

**Comment by gsliepen** [comment]
This has already been merged.

**Comment by gsliepen** [comment]
Oops.

**Comment by gsliepen** [comment]
Sorry about the noise. It was indeed already merged.

**Comment by nicoonoclaste** [comment]
@gsliepen No it's not.
Did you forget to push?

**Comment by gsliepen** [comment]
On Tue, Oct 04, 2016 at 01:15:45PM -0700, Nicolas Braud-Santoni wrote:

> @gsliepen No it's not.
> Did you forget to push?

Ah, that explains a lot. I did push before but not to github. Should be
fixed now.

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by nicoonoclaste** [comment]
Indeed.  Thanks for merging!

**Pull request closed without merging**
